xdebug/vscode-php-debug

README.md, testproject/.vscode/launch.json
without the debugServer switch there was no obvious way for me to debug the adapter.
=> Add note for debugServer setting in launch.json

README.md, package.json, src/phpDebug.ts, src/typings/url-relative/url-relative.d.ts
@gianugo I switched from regexps to using url and path resolve and relative functions, which should be more robust. If you could confirm again that everything works I will merge this.
=> Add sourcemap feature for remote host debugging

README.md, package.json, src/phpDebug.ts, src/test/adapter.ts, src/xdebugConnection.ts
This PR add the ability to configure `max_depth` and `max_children` in launch.json file.
I left the previous values `max_depth` 5 and `max_children` 100 as default.
=> Make max_depth and max_children configurable

README.md, package.json, src/phpDebug.ts, src/test/adapter.ts, typings.json
Closes #33 
@VivPat @apit does this suit you?
=> Add ignore option to ignore paths

README.md
Missing $ sign in pathMappings on Mac OSX
=> Tweak to README.md

src/paths.ts, src/test/paths.ts
It seems like VS Code or another dependency has begun using lowercase drive names in some places, but not in `${workspaceRoot}`
This will make it match up.
=> Fixed Inconsistencies between Drive Paths on Windows (C:\ vs c:\)

src/phpDebug.ts
Move 'started' event after Xdebug settings have been set to make sure that 'run' is not executed before settings are processed and make sure that invalid settings don't prevent init from completing. Add some line feeds to output messages.
The main issue I stumbled on regularly was that because the 'started' event was emitted before the xdebugSettings from launch.json had been processed, occasionally the run command would be sent to Xdebug before the feature_set commands. When the feature_set commands were eventually sent, Xdebug was already in 'stopping' state and returned an error. This error was not caught and resulted in the vscode.InitializedEvent() being missed. This, in turn lead to a situation where the requests were displayed as running in the call stack window but got stuck …
=> fix(phpDebug): Make connection init more robust.

src/phpDebug.ts
Fixes #278 
This sets `evaluateName` on the variable object passed back to vscode.  I guess this is something from a newer version of vscode because I remember the copy used to work.
It sets it to `fullName` for the property if available (which will be something like `$var->property` if it is for a child), or `name` otherwise, which will be for top level variables.
=> fix(phpDebug): Set evaluateName for variables to allow copy

src/phpDebug.ts, src/xdebugConnection.ts
Fixes #164 
Original PR: #292 
This PR reworks how the original one does things after feedback and as noted below.  It made it a lot cleaner to start fresh on a new branch which is why I didn't add the changes on to the original PR...
This introduces a new concept in the xDebug connection:  "execution commands": these are commands that result in PHP being executed.  The way xDebug works, if one of these commands is run, that connection is hung until the PHP code is done executing (until it gets to the next stopping point).  By keeping track of when such commands are still in progress, and making it something that the adapter can check, it allows the adapter to specifically code for when the connection is currently hung.  Which allows preventing the deadlock situation described in #164 …
=> Avoid deadlock with multiple connections when executing code and new connection opens

src/phpDebug.ts, src/xdebugConnection.ts
…f the normal flow
This fixes #301 
Note: there is still the problem that it will seem to "hang" when you continue and the PHP code takes a while to run, #308 will fix that.
=> fix: do not send continue events

src/phpDebug.ts
When the IDE requests a continue operation (step in, out, over, continue) it expects a Response and will remove the current execution position. With XDebug/DBGp the TCP connection will not send a response until another stop condition is encountered this may take an arbitrary amount of time.
This change fixes this by doing some basic validation (is the threadId valid) and then sends a response before executing the continuation command.
Closes #358
=> fix: remove current execution position when performing stop or continue dbgp operation.

src/phpDebug.ts
If "stopOnEntry" is enabled the pause reason will always be "Paused on entry" event if it's the result of a step operation or breakpoint. Resetting the "stopOnEntry" after first use solves the issue. The flag is not used anywhere else.
=> fix: reset "stopOnEntry" after first use to show correct pause reason

src/paths.ts, src/test/paths.ts
I decided to approach #331 and it turned out to be only a minor change. I also added longest prefix matching for the client to debugger mapping as there are use cases for this as well and it does not affect the existing mapping behavior (unless in actual use cases in which the change is most certainly welcome).
=> feat: implement longest prefix matching for pathMappings (closes #331)

.github/workflows/build.yml, ISSUE_TEMPLATE.md, README.md, package.json, src/dbgp.ts, src/paths.ts, src/phpDebug.ts, src/test/adapter.ts, src/xdebugConnection.ts, testproject/.vscode/launch.json
This is not a troll or anything, I was asking myself what's the correct way to write Xdebug and noticed that "XDebug" is mainly used is this extension. Is it intentional?
Source: https://xdebug.org/
=> Fix case: XDebug -> Xdebug

package.json
Fixes #191. Add Configuration doesn't show PHP when selecting `Add Configuration` in a VS Code launch.json file PHP is no longer shown as an option. The new `configurationSnippets` resolves this.
=> fix: add configurationSnippets

src/paths.ts, src/test/paths.ts
Try to detect format of client (IDE) and debugger (Xdebug) path format and explicitly use that instance of path class.
=> fix: Detect IDE path format for convertDebuggerPathToClient

package.json
And also uses the versioned `.vsix` to upload to GitHub Releases.
As in [vscode-shellcheck](https://github.com/timonwong/vscode-shellcheck/blame/3a803d31912b863985405da042339db98fda0c56/release.config.js#L57-L72).
=> chore(release): add marketplace link to release notes

CHANGELOG.md, src/phpDebug.ts
Implement optional stop of debugee after VS Code UI is available from https://github.com/microsoft/vscode/issues/116731
=> feat: Add supportTerminateDebuggee

CHANGELOG.md, package-lock.json, package.json, src/breakpoints.ts, src/phpDebug.ts, src/test/adapter.ts, src/xdebugConnection.ts
Handle breakpoints in async manner.
Better support one (VS Code) to many (Xdebug connections).
Handle busy Xdebug connection.
=> feat: Async Breakpoint Manager

CHANGELOG.md, src/breakpoints.ts, src/phpDebug.ts, src/test/adapter.ts
Request breakpoint info after initialization.
Sync breakpoints to Xdebug connection from internal BreakpointManager state.
Show breakpoints as verified if there are no connections.
Remove _waitingConnections map because the ConfigurationDone handler is not in use anymore.
Cleanup _statuses and _breakpointAdapters to prevent leaks.
Fix typos.
Fix test because the order of startup events changed.
=> fix: Improve breakpoint handling with multiple connections

CHANGELOG.md, package-lock.json, package.json, src/logpoint.ts, src/paths.ts, src/phpDebug.ts, src/test/logpoint.ts
Added support to logpoints. I have very limited knowledge about XDebug protocol, but I believe it does not support anything like the logpoint feature from VSCode. 
So I thought about doing the following:
* add a regular breakpoint
* when breakpoint hit:
* parse message
* send eval command to xdebug for each expression inside curly brackets
* send output to vscode console
* send continue event
closes #258
=> feat: Add support for Logpoints

CHANGELOG.md, src/extension.ts, src/phpDebug.ts
If DBGp initialization fails, disconnect the client, but leave adapter in tact.
=> fix: Improve init failure handling

CHANGELOG.md, src/phpDebug.ts, src/test/adapter.ts
Upon further investigation of #788 and #860, I found that, by default, if "env" is not specified, VSCode does not set it to undefined, but sets it to an empty object `{}`.
The extension code here checks if args.env is not equal to undefined. By logic, undefined is not equal to {} (thanks JavaScript..), thus, with the default "Listen for Xdebug" configuration launched, it will still throw this error needlessly.
I've made a fix for this by, instead, checking if args.env is equal to true (which is the equivalent of !== undefined) - and, **also checks** if there are more than 0 keys in the object, a.k.a the object is not empty. I can confirm that the debugger now runs normally with the default "Listen for Xdebug" configuration in my project.
=> fix: Fixes erroneous non-null args.env check

CHANGELOG.md, src/paths.ts, src/phpDebug.ts, src/test/paths.ts
Allow path mappings like ssh://
=> feat: support uri path mappings

README.md, package.json, src/phpDebug.ts, src/test/adapter.ts, src/xdebugConnection.ts
Add new configuration directive to configure if the debugger should immediately detach/disconnect from a session matching paths defined.
=> feat: Add skipEntryPaths to immediately detach a debug session depending on entry path

package.json
As the PR title suggests, this fixes key bindings collisions with Fullscreen mode.
=> fix: fullscreen keybinding conflict with F11 with activeViewlet

CHANGELOG.md, src/phpDebug.ts, src/test/adapter.ts, src/varExport.ts, src/xdebugConnection.ts
When the IDE requests evaluation with clipboard context use var_export to format the response
=> feat: support clipboard context on variable copy operation
